name: flutter_paymentez_sdk
description: "Manexware Paymentez SDK"
version: 0.0.1
homepage: 'https://www.manexware.com'
repository: 'https://github.com/mangrovex/flutter_paymentez_sdk'
issue_tracker: 'https://github.com/mangrovex/flutter_paymentez_sdk/issues'

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  dio: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3
  very_good_analysis: 5.1.0


flutter:

maintainers:
  - Manuel Vega Ulloa <manuel.vega@manexware.com>